
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

import Header from "@/components/Header";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
const poppins = Inter({ subsets: ["latin"], variable: "--font-poppins" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const dbConnect = await connectMongo();
  // console.log(dbConnect);
  return (
    <html lang="en">
      <body className={cn(inter.className,poppins.className)}>
      <ThemeProvider attribute='class' defaultTheme='system' enableSystem
            disableTransitionOnChange>
         <Header/>
           
      {children}
      <Toaster richColors position="top-center"/>
      </ThemeProvider>
      </body>
    </html>
  );
}
